name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositori
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instal·lar dependències
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || false
        pip install pytest
        pip install unittest
    - name: Executar proves
      run: |
        pytest
        python -m unittest discover
