name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositori
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instal·lar pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Executar proves amb pytest
      run: |
        pytest
